version: "3.9"
services:
  bot:
    build:
      context: ./
      dockerfile: ./cmd/bot/Dockerfile
    environment:
      POSTGRES_DB: discord_bot
    env_file:
      - .env
      - db.env
    depends_on:
      - db_migration
  db_migration:
    build:
      context: ./
      dockerfile: ./cmd/migrate/Dockerfile
    command:
      - /app/migrate
      - "1"
      - "1"
    environment:
      DB_NAME: discord_bot
    env_file:
      - db.env
    depends_on:
      - database
  database:
    container_name: bot-db
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - db.env
